image: php:7.0

cache:
  paths:
  - vendor/

before_script:
    - apt-get -qq update
    - apt-get -qq install wget git unzip > /dev/null
    - wget -N https://getcomposer.org/composer.phar
    - chmod u+x composer.phar
    - ./composer.phar install
    - echo "date.timezone = Europe/Paris" > /usr/local/etc/php/php.ini
    
behat:
  stage: test
  script:
        - ./vendor/bin/behat --init
        - ./vendor/bin/behat --colors