image: php:7.0

stages:
  - test
  - quality

cache:
  paths:
    - vendor/

before_script:
  - apt-get -qq update
  - apt-get -qq install wget git unzip > /dev/null
  - wget -N https://getcomposer.org/composer.phar
  - chmod u+x composer.phar
  - export SYMFONY_ENV=test

behat:
  stage: test
  script:
    - ./composer.phar install --no-interaction
    - echo "date.timezone = Europe/Paris" > /usr/local/etc/php/php.ini
    - ./vendor/bin/behat --init
    - ./vendor/bin/behat --colors

php_cs_fixer:
  stage: quality
  script:
    - wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
    - mv php-cs-fixer-v2.phar php-cs-fixer.phar
    - chmod +x php-cs-fixer.phar
    - ./php-cs-fixer.phar fix --no-interaction --dry-run --diff -v
