image: php:7.0

cache:
  paths:
  - vendor/

before_script:
    - apt-get -qq update
    - wget -N https://getcomposer.org/composer.phar
    - chmod u+x composer.phar
    - ./composer.phar install
    
behat:
  stage: test
  script:
        - ./vendor/bin/behat --init
        - ./vendor/bin/behat --colors