language: php

php:
    - 7.1

cache:
    apt: true
    directories:
        - vendor
        - $HOME/.composer/cache

install:
    - wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar
    - mv php-cs-fixer-v2.phar php-cs-fixer.phar
    - chmod +x php-cs-fixer.phar

before_script:
    - export SYMFONY_ENV=test
    - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update --no-progress

script:
    - composer install --no-interaction --no-progress
    - ./vendor/bin/behat
    - ./php-cs-fixer.phar fix --no-interaction --dry-run --diff -v
