version: '2'

services:
  db:
    environment:
      POSTGRES_DB: p-api
      POSTGRES_PASSWORD: postgres
    image: postgres:9-alpine
    volumes:
      - db-data:/var/lib/postgresql
  nginx:
    image: nginx:1.11-alpine
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web:/srv/api-platform/web
  php:
    build: .
    depends_on:
      - db
    environment:
      SYMFONY_ENV: prod
    volumes:
      - ./:/srv/api-platform
      - ./var/cache:/srv/api-platform/var/cache
      - ./var/logs:/srv/api-platform/var/logs
      - ./var/sessions:/srv/api-platform/var/sessions
      - ./var:/srv/api-platform/var
      - ./vendor:/srv/api-platform/vendor
      - ./web:/srv/api-platform/web

volumes:
  db-data: {}