services:
    video.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', title: 'ipartial', channel: 'ipartial', magnet: 'ipartial', hash: 'ipartial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'video.search' } ]

    account.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', username: 'ipartial', email: 'ipartial', firstName: 'ipartial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'account.search' } ]

    channel.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', name: 'ipartial', account: 'ipartial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'channel.search' } ]

    view.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { video: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'view.search' } ]

    metadata.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { location: 'exact' } ]
        tags:      [ { name: 'api_platform.filter', id: 'metadata.search' } ]

