security:
    encoders:
        AppBundle\Entity\Account:
            algorithm: sha512
            encode_as_base64: true
            iterations: 5000

    providers:
        account_provider:
            entity:
                class: AppBundle\Entity\Account

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        main:
            pattern: ^/
            fos_oauth: true
            stateless: true
            anonymous: true

    access_control:
        - { path: "^/$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/videos", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/categories", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/", roles: IS_AUTHENTICATED_FULLY }
