security:
    encoders:
        AppBundle\Entity\Account:
              algorithm: sha512
              encode_as_base64: true
              iterations: 5000

    providers:
        account_provider:
            entity:
                class: AppBundle\Entity\Account

    firewalls:
        dev:
            pattern: ^/((profiler|wdt)|css|images|js)/
            security: false
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        api_doc:
            pattern: ^/api/doc
            security: false
        main:
            pattern: ^/
            fos_oauth: true
            stateless: true
    access_control:
        - { path: ^/videos, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/, roles: [ IS_AUTHENTICATED_FULLY ] }
