services:
    app.access_listener:
        class: AppBundle\Listener\AccessListener
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }
