services:
    app.listener.access_listener:
        class: AppBundle\Listener\AccessListener
        arguments: [ "@app.security.rate_limiter", "%kernel.environment%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.listener.response_listener:
        class: AppBundle\Listener\ResponseListener
        arguments: [ "@app.security.rate_limiter", "%kernel.environment%" ]
        tags:
            - { name: kernel.event_listener, event: kernel.response }

    app.security.account_provider:
        class: AppBundle\Security\AccountProvider
        arguments: [ "@doctrine.orm.entity_manager" ]
        public: false

    app.security.rate_limiter:
        class: AppBundle\Security\RateLimiter
        arguments: [ "@doctrine.orm.entity_manager" ]

    app.security.account_voter:
        class: AppBundle\Security\AccountVoter
        tags:
            - { name: security.voter }

    app.event_subscriber.account_checker:
        class: AppBundle\EventSubscriber\AccountChecker
        arguments: [ "@security.authorization_checker" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    app.event_subscriber.password_encryption:
        class: AppBundle\EventSubscriber\PasswordEncryption
        tags:
            - { name: kernel.event_listener, event: kernel.view }
