services:
    app.access_listener:
        class: AppBundle\Listener\AccessListener
        arguments: [ "@doctrine.orm.entity_manager" ]
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    video.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', title: 'partial', channel: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'video.search' } ]

    account.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', username: 'partial', email: 'partial', firstName: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'account.search' } ]

    channel.search_filter:
        parent:    'api_platform.doctrine.orm.search_filter'
        arguments: [ { id: 'exact', name: 'partial', account: 'partial' } ]
        tags:      [ { name: 'api_platform.filter', id: 'channel.search' } ]